services:
  - type: web
    name: vision-analysis-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: AZURE_STORAGE_CONNECTION_STRING
        sync: false
      - key: VISION_ENDPOINT
        sync: false
      - key: VISION_KEY
        sync: false
    autoDeploy: true